import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../dist/server/index.js';
function environment(){const db=new DatabaseSync(':memory:');db.exec(readFileSync('drizzle/0000_opposite_serpent_society.sql','utf8'));const files=new Map();return {DB:{prepare(sql){const bound=(args=[])=>({bind(...params){return bound(params)},async first(){return db.prepare(sql).get(...args)||null},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}});return bound()}},BUCKET:{async put(k,v){files.set(k,v)},async get(k){return files.has(k)?{body:files.get(k)}:null},async delete(k){files.delete(k)}},ASSETS:{fetch:async()=>new Response('static')}}}
const request=(path='/api/project',method='GET',body,owner='client-a',origin='https://portal.test')=>new Request('https://portal.test'+path,{method,headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),origin,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});
test('anonymous users cannot read or mutate project data',async()=>{const env=environment();assert.equal((await worker.fetch(request('/api/project','GET',undefined,''),env)).status,401);assert.equal((await worker.fetch(request('/api/project','POST',{type:'approval',id:'design',status:'Approved'},''),env)).status,401)});
test('cross-origin changes are rejected',async()=>{const env=environment();assert.equal((await worker.fetch(request('/api/project','POST',{type:'approval',id:'design',status:'Approved'},'client-a','https://evil.test'),env)).status,403)});
test('approvals persist, produce a decision record, and stay isolated by client',async()=>{const env=environment();const result=await worker.fetch(request('/api/project','POST',{type:'approval',id:'design',status:'Approved'}),env);assert.equal(result.status,200);const a=await (await worker.fetch(request(),env)).json();assert.equal(a.approvals[0].status,'Approved');assert.match(a.decisions[0].title,/approved/);const b=await (await worker.fetch(request('/api/project','GET',undefined,'client-b'),env)).json();assert.equal(b.approvals[0].status,'Awaiting approval')});
test('concurrent feedback updates are not lost and repeated IDs do not duplicate',async()=>{const env=environment();const ids=[crypto.randomUUID(),crypto.randomUUID()];await Promise.all(ids.map(id=>worker.fetch(request('/api/project','POST',{type:'feedback-add',id,target:'hero-heading',text:'A helpful revision',x:20,y:30}),env)));const s=await(await worker.fetch(request(),env)).json();assert.equal(s.feedback.filter(f=>ids.includes(f.id)).length,2);await worker.fetch(request('/api/project','POST',{type:'feedback-add',id:ids[0],target:'hero-heading',text:'A helpful revision',x:20,y:30}),env);const next=await(await worker.fetch(request(),env)).json();assert.equal(next.feedback.filter(f=>f.id===ids[0]).length,1)});
test('invalid staging URLs and empty feedback are rejected',async()=>{const env=environment();for(const body of [{type:'settings',name:'FABRIPASS',motion:true,notifications:true,stagingUrl:'javascript:alert(1)'},{type:'settings',name:'FABRIPASS',motion:true,notifications:true,stagingUrl:'https://'},{type:'feedback-add',id:crypto.randomUUID(),target:'hero-heading',text:'  ',x:0,y:0}])assert.equal((await worker.fetch(request('/api/project','POST',body),env)).status,400)});
test('uploaded file bytes are retained and other clients cannot download them',async()=>{const env=environment();const form=new FormData();form.set('file',new File(['asset contents'],'brand.txt',{type:'text/plain'}));form.set('category','Brand');const result=await worker.fetch(request('/api/assets','POST',form),env);assert.equal(result.status,200);const data=await result.json();const asset=data.assets[0];const file=await worker.fetch(request('/api/assets/'+asset.id),env);assert.equal(await file.text(),'asset contents');assert.match(file.headers.get('content-disposition'),/attachment/);assert.equal((await worker.fetch(request('/api/assets/'+asset.id,'GET',undefined,'client-b'),env)).status,404)});
